import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Link from 'next/link';
import { Tab } from '@headlessui/react';
import Masonry from 'react-masonry-css';
import classNames from 'classnames'

import game1 from '../public/game1.png'
import game2 from '../public/game2.png'
import game3 from '../public/game3.png'
import game4 from '../public/game4.png'
import game5 from '../public/game5.png'
import game6 from '../public/game6.png'
import game7 from '../public/game7.png'
import game8 from '../public/game8.png'
import game9 from '../public/game9.png'
import game10 from '../public/game10.png'
import { redirect } from 'next/dist/server/api-utils';


const inter = Inter({ subsets: ['latin'] })

const tabs = [
  {
    key: 'all',
    display: 'All Games'
  },
  {
    key: 'code.org',
    display: 'Code.org'
  },
  {
    key: 'scratch',
    display: 'Scratch'
  },
  {
    key: 'replit',
    display: 'Replit'
  },
  {
    key: 'p5.js',
    display: 'p5.js'
  }
];

const allGames = [game1, game2, game3, game4, game5, game6, game7, game8, game9, game10];
const codeGames = [game1, game2, game8];
const scratchGames = [game4, game7];
const replitGames = [game3, game5, game6, game9];
const p5Games = [game10];
const allGameLinks = [
  "https://studio.code.org/projects/applab/8al2mTiqYVYH8FALbWIB8vp6ipjPvTZM0RCmJTSwtCU",
  "https://studio.code.org/projects/applab/fQuGLh8ePO-i3tJ2zrjnNctaMhAFeIfnvZPqHHScPP4",
  "https://replit.com/@avneets/Everything-Project-III-Quiz?v=1",
  "https://scratch.mit.edu/projects/775238916",
  "https://multidimensionalsanta.racchen.repl.co/",
  "https://replit.com/@shuchid/Hangman-Christmas-Edition#main.py",
  "https://scratch.mit.edu/projects/765963500",
  "https://studio.code.org/projects/applab/5XOaBaihvr-5yFR0B5H08Y99w8nGnEQIweyObhHgyZM",
  "https://replit.com/@Vicbel/Santa-Survival-Adventure?v=1",
  "https://editor.p5js.org/inkjelly/full/Iz4yEVIjJ"
];
const codeGameLinks = [
  "https://studio.code.org/projects/applab/8al2mTiqYVYH8FALbWIB8vp6ipjPvTZM0RCmJTSwtCU",
  "https://studio.code.org/projects/applab/fQuGLh8ePO-i3tJ2zrjnNctaMhAFeIfnvZPqHHScPP4",
  "https://studio.code.org/projects/applab/5XOaBaihvr-5yFR0B5H08Y99w8nGnEQIweyObhHgyZM"
];

const scratchGameLinks = [
  "https://scratch.mit.edu/projects/775238916",
  "https://scratch.mit.edu/projects/765963500"
];
const replitGameLinks = [
  "https://replit.com/@avneets/Everything-Project-III-Quiz?v=1",
  "https://multidimensionalsanta.racchen.repl.co/",
  "https://replit.com/@shuchid/Hangman-Christmas-Edition#main.py",
  "https://replit.com/@Vicbel/Santa-Survival-Adventure?v=1"
];
const p5GameLinks = [
  "https://editor.p5js.org/inkjelly/full/Iz4yEVIjJ"
];
const openLink = (url: string | URL | undefined) => {
  window.open(url, '_blank', 'noreferrer');
};

export default function Home() {
  return (
    <div className = "h-full bg-black overflow-auto">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className ="fixed bg-stone-900 top-0 w-full z-10 flex justify-between items-center h-[90px] px-10">
        <span className = "uppercase text-lg font-medium">Girls Who Code Christmas Game Jam</span>
        <Link href="https://www.facebook.com/groups/331081594733054" className="rounded-3xl bg-lime-50 text-stone-900 px-3 py-2 hover:bg-opacity-90">Get in Touch</Link>
        
      </header>

      <main className = "pt-[110px]">
        <div className="flex flex-col items-center h-full">
          <Tab.Group>
            <Tab.List className="flex items-center gap-12">

              {tabs.map(tab => (
                <Tab key={tab.key} className="p-2">
                  {({selected}) => (<span className={classNames ("uppercase text-lg", selected ? 'text-red-500' : 'text-stone-600')}>{tab.display}</span>)}
                </Tab>
              ))}

            </Tab.List>
            <Tab.Panels className="h-full h-full max-w-[900px] w-full p-2 sm:p-4 my-6">
              <Tab.Panel>
                <Masonry breakpointCols={2} className='flex gap-4' columnClassName=''>

                  {allGames.map((image, idx) => 
                    <Image 
                      key={image.src} 
                      src={image} 
                      alt="placeholder" 
                      className="my-6 rounded- hover:scale-105 transition duration-300 ease-in-out" 
                      placeholder="blur"
                      onClick={()=> {
                        openLink(allGameLinks[idx]);
                      }}
                    />
                    
                  )}
              
                </Masonry>

              </Tab.Panel>
              <Tab.Panel>
                <Masonry breakpointCols={2} className='flex gap-4' columnClassName=''>

                  {codeGames.map((image, idx) => 
                    <Image 
                      key={image.src} 
                      src={image} 
                      alt="placeholder" 
                      className="my-6 rounded- hover:scale-105 transition duration-300 ease-in-out" 
                      placeholder="blur"
                      onClick={()=> {
                        openLink(codeGameLinks[idx]);
                      }}
                    />
                    
                  )}
              
                </Masonry>

              </Tab.Panel>
              <Tab.Panel>
                <Masonry breakpointCols={2} className='flex gap-4' columnClassName=''>

                  {scratchGames.map((image, idx) => 
                    <Image 
                      key={image.src} 
                      src={image} 
                      alt="placeholder" 
                      className="my-6 rounded- hover:scale-105 transition duration-300 ease-in-out" 
                      placeholder="blur"
                      onClick={()=> {
                        openLink(scratchGameLinks[idx]);
                      }}
                    />
                    
                  )}
              
                </Masonry>

              </Tab.Panel>
              <Tab.Panel>
                <Masonry breakpointCols={2} className='flex gap-4' columnClassName=''>

                  {replitGames.map((image, idx) => 
                    <Image 
                      key={image.src} 
                      src={image} 
                      alt="placeholder" 
                      className="my-6 rounded- hover:scale-105 transition duration-300 ease-in-out" 
                      placeholder="blur"
                      onClick={()=> {
                        openLink(replitGameLinks[idx]);
                      }}
                    />
                    
                  )}
              
                </Masonry>

              </Tab.Panel>
              <Tab.Panel>
                <Masonry breakpointCols={2} className='flex gap-4' columnClassName=''>

                  {p5Games.map((image, idx) => 
                    <Image 
                      key={image.src} 
                      src={image} 
                      alt="placeholder" 
                      className="my-6 rounded- hover:scale-105 transition duration-300 ease-in-out" 
                      placeholder="blur"
                      onClick={()=> {
                        openLink(p5GameLinks[idx]);
                      }}
                    />
                    
                  )}
              
                </Masonry>

              </Tab.Panel>
              

            </Tab.Panels>
          </Tab.Group>
        </div>
        
      </main>

      <footer className="h-[90px] flex justify-center items-center text-lg font-medium">
        <p>phhsgirlswhocode@gmail.com</p>
      </footer>
    </div>
  );
}
